Bug fixed
File "/opt/gamelogserver/GameLogServer/log_resource.py", line 15, in get
    'length': 0 if content is None else len(content),
TypeError: object of type 'bool' has no len()